/*!
 * Copyright (c) Microsoft Corporation.
 * All rights reserved. See LICENSE in the project root for license information.
 */

import { buildMockModuleProps } from '@msdyn365-commerce/core-internal';
/// <reference types="jest" />

import * as React from 'react';
import * as renderer from 'react-test-renderer';

import ProductFeature from '../product-feature';
import { IProductFeatureData } from '../product-feature.data';
import { IProductFeatureConfig, IProductFeatureProps } from '../product-feature.props.autogenerated';
import { AsyncResult, SimpleProduct } from '@msdyn365-commerce/retail-proxy';

const mockData: IProductFeatureData = {
    products: [
        {
            status: 'SUCCESS',
            result: {
                RecordId: 12345,
                Name: 'Sample Product',
                ProductTypeValue: 1,
                Price: 99.99
            } as SimpleProduct
        } as AsyncResult<SimpleProduct>
    ]
};

const mockConfig: IProductFeatureConfig = {
    productTitle: 'Featured Product',
    productDetails: '',
    buttonText: 'Buy Now',
    productIds: '12345'
};

const mockActions = {};

describe('ProductFeature', () => {
    let moduleProps: IProductFeatureProps<IProductFeatureData>;
    beforeAll(() => {
        moduleProps = buildMockModuleProps(mockData, mockActions, mockConfig) as IProductFeatureProps<IProductFeatureData>;
    });
    it('renders correctly', () => {
        const component: renderer.ReactTestRenderer = renderer.create(<ProductFeature {...moduleProps} />);
        const tree: renderer.ReactTestRendererJSON | renderer.ReactTestRendererJSON[] | null = component.toJSON();
        expect(tree).toMatchSnapshot();
    });
});
